version: '2'

services:

  nginx:
    build: 
      context: .
      dockerfile: Dockerfile4Development
    container_name: dev-www.cismet.de
    image: cismet/main-website:latest
    restart: always
    network_mode: bridge
    volumes:
        - ./:/src
    ports:
        - "4567:4567"
        - "8888:80"
