version: "2"

services:
  nginx:
    image: zeroplusx/middleman
    container_name: dev-www.cismet.de
    restart: always
    network_mode: bridge
    volumes:
      - ./:/src
    command: server --watcher-force-polling --watcher-latency=1
    ports:
      - "4567:4567"
      - "8888:80"
